version: "3"

services:
  app:
    build: .
    restart: always
    volumes:
      - ./data:/home/data
    command:
      - python word_count.py data/input.txt


  test:
    build: .
    restart: always
    command:
      - cd tests/
      - python simple_testing.py

volumes:
  data: