version: "3"

services:
  app:
    build: .
    restart: always
    volumes:
      - ./data:/home/data
    command:
      - ./run.sh


  test:
    build: .
    restart: always
    command:
      - cd tests/
      - ./test.sh

volumes:
  data: